## REDE A - Rede Interna (LAN)
pc1[0]=A
pc2[0]=A
fw[1]=A

## REDE B - DMZ
web[0]=B
dns[0]=B
fw[2]=B

## REDE C - Rede de Gerenciamento
adm[0]=C
fw[3]=C

## REDE D - Firewall
fw[0]=D
r0[0]=D

## REDE E - (Internet) WAN Roteador de borda
r0[1]="internet"